Add popup
BereketRetta/MicroversePortfolio pull request #16
Opened 2021-12-21 13:12 UTC by BereketRetta

2021-12-21 13:27 UTC, elyor-doniyorov reviewed
Hi @BereketRetta and @myelin0, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has no JavaScript linters, but only has HTML, CSS.
KIndly add Javascript linters too!

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2021-12-21 16:06 UTC, julie-ify requested changes
## Hi Team, 

Good job so far!

Highlight!
- Good feature branch name ✔️ 
- No linter errors ✔️  

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️⛔️
_Check the comments under the review._

- [ ] Please consider checking out this [link ](https://www.freecodecamp.org/news/writing-good-commit-messages-a-practical-guide/) to learn how to write good commit messages. This will help you to write the correct commit messages when you get your dream job.

- [ ] Currently, your app shows this when I try to find the mobile and desktop breakpoint. Please consider fixing it.

<img width="392" alt="chrome_95IMWpG82Y" src="https://user-images.githubusercontent.com/81468675/146960902-e1d5d392-9e84-47a0-b5d3-a2763100bd52.png">



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-21 16:06 UTC, julie-ify commented on index.js
> +
- [x] Consider creating an array of objects with each object containing each of your projects. You have 6 project cards so you should have 6 objects in the array each containing the details of your projects. This will make adding projects in the future easy. You will only add it in one place - as another object in the projects array.

Example: 
```javascript
const projects = [
{
    name: "ProjectOne",
    description: "Description for project one",
    image: "link_to_image.jpg",
    technologies: ["Phaser3", "JavaScript", "Jest"],
    live-version: "link_to_live_version.com",
    source: "link_to_live_version",

}
{
    name: "ProjectTwo",
    description: "Description for project two",
    image: "link_to_image.jpg",
    technologies: ["Html", "JavaScript", "CSS"],
    live-version: "link_to_source code",
    source: "link_to_source code",
}
...
]
```

2021-12-21 16:06 UTC, julie-ify commented on index.js
> +<button><a href='#' target='_blank'>See Source</a><span><img src='./images/Git.png' alt='github'></span></button>
- [x] Consider adding the link to the live version, and link to the project source code to the array containing the projects and dynamically use it here.
- [x] Also use the correct color for the button text to match your design template.

Your design:
<img width="281" alt="chrome_bLDhgqUITJ" src="https://user-images.githubusercontent.com/81468675/146958954-eaa778d8-9af9-43a6-894f-48c6bce11561.png">


Figma design:
<img width="407" alt="chrome_lnuKDCapiQ" src="https://user-images.githubusercontent.com/81468675/146958936-97f85c7f-c83e-4830-8b8e-7e142af4adf1.png">

2021-12-21 16:06 UTC, julie-ify commented on index.js
> +</ul>
[Optional] 

- Consider looping through all these list items instead of repeating them. This is to ensure that your code is simple and dry.

2021-12-22 09:15 UTC, Cathella approved these changes
## Approved 🟢🎉

### Hi @BereketRetta ✋🏻, 

You have done a great job making changes requested by the previous reviewer 💪🏻.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-22 09:19 UTC, merged