Mobile styling
BereketRetta/MicroversePortfolio pull request #7
Opened 2021-12-03 15:16 UTC by BereketRetta

This is the mobile version for the portfolio website

2021-12-03 17:09 UTC, HENRYKC24 requested changes
## Hi @BereketRetta :wave:, 

### Good job so far:+1:
![around the corner](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Highlight!
- Close to perfect mobile version ✔️
- Enormous effort exerted ✔️
- Clean code ✔️
- Superb CSS ✔️

# Required Changes ♻️ ⛔️
While you made a frantic effort in this project, there are some issues that you still need to address.!
- [ ] You need to document our project professionally. Missing in your README.md file are :point_down:
1. The description of your readme file only reads "This is a simple hello world project". 
![image](https://user-images.githubusercontent.com/45668340/144644212-4e8d252f-7090-48ed-8a8b-826a082f7bbc.png)
2. Please, we can enumerate the processes for running the app locally. This is a good documentation approach and it will give you credit when a recruiter views your project.
![image](https://user-images.githubusercontent.com/45668340/144644432-c4368e57-7d5d-4dba-aa54-62bc097f54a2.png)
3. Having a link to the issue page is very necessary for your readme file. Please, let's try to add one.
![image](https://user-images.githubusercontent.com/45668340/144644658-e89b8888-3a51-4280-b3fa-1174f92f1c5d.png)
- [ ] I also noticed that your LinkedIn link is not working. Please, check what is breaking the link.
- [ ] There is apparently a missing MIT Licence file in your project. Please add it.
![image](https://user-images.githubusercontent.com/45668340/144644939-4f21748c-9bf8-4c12-b883-9c27801c42ae.png)
![image](https://user-images.githubusercontent.com/45668340/144645006-ee4ce28e-3039-4f3b-97f5-d1a487582b12.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-03 17:09 UTC, HENRYKC24 commented on index.html
> +          <div class="placeholder"></div>
I will not fail to commend you for making sure you stick to the project requirement and adherence to quality code :+1: 
You nailed this part :dart: Your code is clean:ok_hand:
:clap: :clap: :clap:

2021-12-03 17:09 UTC, HENRYKC24 commented on mobile.css
> +  flex-direction: column;
You also made use of the `grid` and `flex` CSS properties to style the elements as required. Good job:+1:

2021-12-04 03:34 UTC, carlos-ssh commented
# 🚫⚠️🛑 INVALID SUBMISSION 🚫⚠️🛑
Hi <STUDENT_MENTION>, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is missing the features requested by the last reviewer. Kindly improve your `README` file and request another code review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2021-12-04 03:51 UTC, BereketRetta commented
@carlos-ssh I have improved all the readme requirements just now can you re-check it for me, please

2021-12-04 03:53 UTC, ShoiraTa commented
Hi @BereketRetta , I am reviewing your code, but I cannot see improved `readme`, maybe you did not push the changes ?

2021-12-04 03:55 UTC, BereketRetta commented
dear @ShoiraTa, I have pushed the changes onto main

2021-12-04 03:57 UTC, BereketRetta commented
<img width="953" alt="Screen Shot 2021-12-04 at 6 56 23 AM" src="https://user-images.githubusercontent.com/47314387/144696030-bc728879-aa0d-4fd9-ae00-1d576f746e12.png">

2021-12-04 03:58 UTC, BereketRetta commented
@ShoiraTa should I submit another review

2021-12-04 03:58 UTC, ShoiraTa commented
I have seen now, please change the name of the project its still hello world 😁, and please next time do not push chnages directly to main, all files should be pushed after review 😉

2021-12-04 03:58 UTC, ShoiraTa commented
### **STATUS: APPROVED  ✔️** 
------
Hi @BereketRetta ,  

Your project is complete!  Congratulations!  🎉💯🌟 

<img src="https://www.serialminds.com/wp-content/uploads/2015/11/loser.gif" width="400" height="250" />

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-04 03:59 UTC, ShoiraTa commented
No need to submit for another review, please check your dashboard, I have approved it  👍🏻

2021-12-04 04:00 UTC, BereketRetta commented
Thank you!

2021-12-04 04:21 UTC, carlos-ssh commented
I checked up again and still missing the readme update. 

- Kindly check the readme file from this branch and you will see that this readme contains information from another project.

2021-12-07 12:52 UTC, carlos-ssh commented
# 🚫⚠️🛑 INVALID SUBMISSION 🚫⚠️🛑
Hi @BereketRetta , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that your Pull Request it's approved. Kindly open a new pull request.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2021-12-07 12:57 UTC, merged